### ISSUE TITLE
Congestion data for Brazil and Sao Paulo: dashboard chart not matching data in file.

### ISSUE THREAD

**Issue by fkawaoka** [EL-BID/IDB-IDB-Invest-Coronavirus-Impact-Dashboard#11]
This may be an issue with the IDB dashboard rather than with the actual data available in GitHub. Dashboard charts for Brazil and Sao Paulo metropolitan area do not seem to match numbers in the data file in GitHub (manually downloaded). They also do not seem to match the same graphs as they were available just a few days ago.

**Comment by JoaoCarabetta** [comment]
Hi @fkawaoka ,

Sorry for my late response. It is now updated and matching. 

Can you check it out to see if everything is ok?

**Comment by fkawaoka** [comment]
Hi @JoaoCarabetta , they do match now. Thank you.
