### ISSUE TITLE
polygons in the new version of the dataset

### ISSUE THREAD

**Issue by michelszklo** [EL-BID/IDB-IDB-Invest-Coronavirus-Impact-Dashboard#16]
Hi,
I noticed that in the new version of the dataset the variable that contained the polygons of each region_slug is missing. Would it be possible to add it again? This variable is really helpful when we try to merge the TCI dataset with others

Thanks

**Comment by JoaoCarabetta** [comment]
Hi @michelszklo, the polygons are now in the metadata table.

https://docs.google.com/spreadsheets/d/16SIYidLScgFZOeqpHmAo_u_rFmuxxpCCWeRAXSDOT3I/edit#gid=2042095793

**Comment by michelszklo** [comment]
Thanks, @JoaoCarabetta !
