### ISSUE TITLE
[Region Request] <add short description>

### ISSUE THREAD

**Issue by martin1891** [EL-BID/IDB-IDB-Invest-Coronavirus-Impact-Dashboard#29]
Hey!

To request new regions you have to generate a .csv with the format of [this](https://docs.google.com/spreadsheets/d/1rwM3kZEPrpjUwugTQ0kGhkWaqaJ0ZG7o0lH8hjojiHA/edit?usp=sharing) template.

You can just copy the spreadsheet, add your regions and share it back. 

Also, let us know what are your plans with these regions! We might get you some extra help or connect you with similar projects.

We run the pipeline daily. So, after the regions are accepted, expect the output the next day at the same url with the `region_slug` that you set.

Request content
------------------

Regions spreadsheet link: <link>

I need these regions because: <motive>

**Comment by JoaoCarabetta** [comment]
Hi @martin1891,

both of these cities already exists in the database under the slugs `arequipa` and `aguascalientes`.

Refer to **Use the data** section of the README to see how to download the data.
