### ISSUE TITLE
region_slug "natal" is receiving data from region_slug "fortaleza"

### ISSUE THREAD

**Issue by michelszklo** [EL-BID/IDB-IDB-Invest-Coronavirus-Impact-Dashboard#4]
Hi,
I noticed that when importing data through R the columns population, ratio_20 and region_shapefile_wkt of the region_slug == 'natal' are receiving data from the region_slug == 'fortaleza'

**Comment by JoaoCarabetta** [comment]
Thanks! I will change for the next update
