### ISSUE TITLE
Requesting Data

### ISSUE THREAD

**Issue by Datalcoholic** [EL-BID/IDB-IDB-Invest-Coronavirus-Impact-Dashboard#5]
Hi, my name is Raul and i work as data scientist, I'm from Venezuela, as you know we are suffering of gas shortage and that is forcing so many venezuelans to queue outside of gas stations waiting to refill  , it there a way that you can share the data of this gatherings ???

**Comment by ErickGB** [comment]
How is ratio_20 interpreted? what is the scale
Example:
tijuana Central America 2020-03-09 with 0.67326473
tijuana Central America 2020-04-02 with 56.2614195

this change represents a growth of 8256% .. is that correct?

**Comment by JoaoCarabetta** [comment]
Hi @ErickGB , 

Tijuana is actually a clear case of awful Waze data. We almost ready to release a version that takes out/treat cities with poor data. 

If you see trends like that, it probably means that the Waze data for that location is not reliable. 

@Datalcoholic , I don't think we will be able to produce data for very tiny regions like the one that you are asking us. If you do work with the city government, you can contact Waze directly via Waze for Cities to request access to the data.
